# Generated by Django 3.1.4 on 2021-01-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minichua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mini',
            name='tags',
        ),
        migrations.AddField(
            model_name='mini',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='minichua.Tags'),
        ),
    ]
